name: mmgaze_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8  
  - pip
  - numpy=1.23.5
  - scipy=1.9.1
  - pandas=1.3.5
  - scikit-learn=1.1.2
  - matplotlib=3.5.3
  - seaborn=0.11.2
  - opencv-python=4.6.0.66
  - imageio=2.21.1
  - h5py=3.10.0
  - protobuf=3.20.3
  - pillow=9.2.0
  - tqdm=4.65.2
  - pycocotools=2.0.7
  - mmengine=0.10.1
  - timm=0.6.7
  - openmim=0.3.9
  - matplotlib-inline
  - ipython
  - ipykernel
  - jupyterlab
  - notebook
  - pip:
      - addict==2.4.0
      - imgaug==0.4.0
      - mmcv-full  
      - mmdet      
